name: Test
 
on:
  
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

jobs:
 
  build:
    
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      
      - name: dependecies
        run: sudo apt install python3 python3-pip python3-dev && curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=stable

      # Runs a set of commands using the runners shell
      - name: pip
        run: pip3 install setuptools wheel setuptools-rust requests
      
      - name: compile
        run: python3 setup.py install --user
